web-app-asp-net-mvc-code-first/Models/Entities/StoreBranch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web.Mvc;
using web_app_asp_net_mvc_code_first.Models.Attributes;
using web_app_asp_net_mvc_code_first.Extensions;
using web_app_asp_net_mvc_code_first.Models.Enums;

namespace web_app_asp_net_mvc_code_first.Models.Entities
{
    public class StoreBranch
    {
        /// <summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Название филиала
        /// </summary>    
        [Required]
        [Display(Name = "Название филиала", Order = 5)]
        public string StoreBranchName { get; set; }

        /// <summary>
        /// Время работы
        /// </summary>    
        [Required]
        [Display(Name = "Время работы", Order = 5)]
        public string WorkingHours { get; set; }

        /// <summary>
        /// Регион
        /// </summary> 
        [ScaffoldColumn(false)]
        public Region Region { get; set; }

        [Display(Name = "Регион", Order = 50)]
        [UIHint("DropDownList")]
        [TargetProperty("Region")]
        [NotMapped]
        public IEnumerable<SelectListItem> RegionDictionary
        {
            get
            {
                var dictionary = new List<SelectListItem>();

                foreach (Region type in Enum.GetValues(typeof(Region)))
                {
                    dictionary.Add(new SelectListItem
                    {
                        Value = ((int)type).ToString(),
                        Text = type.GetDisplayValue(),
                        Selected = type == Region
                    });
                }

                return dictionary;
            }
        }

        /// <summary>
        /// Город
        /// </summary> 
        [ScaffoldColumn(false)]
        public int CityId { get; set; }
        [ScaffoldColumn(false)]
        public virtual City City { get; set; }

        [Display(Name = "Город", Order = 50)]
        [UIHint("DropDownList")]
        [TargetProperty("CityId")]
        [NotMapped]
        public IEnumerable<SelectListItem> CityDictionary
        {
            get
            {
                var db = new StoreContext();
                var query = db.Cities;

                if (query != null)
                {
                    var dictionary = new List<SelectListItem>();
                    dictionary.AddRange(query.OrderBy(d => d.Name).ToSelectList(c => c.Id, c => c.Name, c => c.Id == CityId));
                    return dictionary;
                }

                return new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } };
            }
        }

        /// <summary>
        /// Продукты
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<Product> Products { get; set; }

        /// <summary>
        /// Города
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<City> Cities { get; set; }
    }
}

web-app-asp-net-mvc-code-first/Controllers/StoreBranchesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using web_app_asp_net_mvc_code_first.Models;
using web_app_asp_net_mvc_code_first.Models.Entities;

namespace web_app_asp_net_mvc_code_first.Controllers
{
    public class StoreBranchesController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new StoreContext();
            var store_branches = db.StoreBranches.ToList();

            return View(store_branches);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var store_branch = new StoreBranch();
            return View(store_branch);
        }

        [HttpPost]
        public ActionResult Create(StoreBranch model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new StoreContext();

            db.StoreBranches.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/StoreBranches/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new StoreContext();
            var store_branch = db.StoreBranches.FirstOrDefault(x => x.Id == id);
            if (store_branch == null)
                return RedirectPermanent("/StoreBranches/Index");

            db.StoreBranches.Remove(store_branch);
            db.SaveChanges();

            return RedirectPermanent("/StoreBranches/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new StoreContext();
            var store_branch = db.StoreBranches.FirstOrDefault(x => x.Id == id);
            if (store_branch == null)
                return RedirectPermanent("/StoreBranches/Index");

            return View(store_branch);
        }

        [HttpPost]
        public ActionResult Edit(StoreBranch model)
        {
            var db = new StoreContext();
            var store_branch = db.StoreBranches.FirstOrDefault(x => x.Id == model.Id);
            if (store_branch == null)
                ModelState.AddModelError("Id", "Продукт не найден");

            if (!ModelState.IsValid)
                return View(model);

            MappingStoreBranch(model, store_branch);

            db.Entry(store_branch).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/StoreBranches/Index");
        }

        private void MappingStoreBranch(StoreBranch sourse, StoreBranch destination)
        {
            destination.StoreBranchName = sourse.StoreBranchName;
            destination.WorkingHours = sourse.WorkingHours;
            destination.CityId = sourse.CityId;
            destination.City = sourse.City;
            destination.Region = sourse.Region;
        }
    }
}

web-app-asp-net-mvc-code-first/Views/StoreBranches/Create.cshtml
@using web_app_asp_net_mvc_code_first.Models.Entities
@model StoreBranch

<h3>Филиал</h3>

@using (Html.BeginForm("Create", "StoreBranches", FormMethod.Post))
{
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" />
    @Html.ActionLink("Отменить", "Index", "StoreBranches")
}

web-app-asp-net-mvc-code-first/Views/StoreBranches/Edit.cshtml
@using web_app_asp_net_mvc_code_first.Models.Entities
@model StoreBranch

<h3>Филиал</h3>

@using (Html.BeginForm("Edit", "StoreBranches", FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" />
    @Html.ActionLink("Отменить", "Index", "StoreBranches")
}

web-app-asp-net-mvc-code-first/Views/StoreBranches/Index.cshtml
@using web_app_asp_net_mvc_code_first.Models.Entities
@using web_app_asp_net_mvc_code_first.Extensions
@model List<StoreBranch>

<h3>Филиалы</h3>

@Html.ActionLink("Добавить запись", "Create", "StoreBranches")

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                Название филиала
            </th>
            <th>
                Время работы
            </th>
            <th>
                Регион
            </th>
            <th>
                Город
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var store_branch in Model)
        {
            <tr>
                <td>
                    @store_branch.StoreBranchName
                </td>
                <td>
                    @store_branch.WorkingHours
                </td>
                <td>
                    @store_branch.Region.GetDisplayValue()
                </td>
                <td>
                    @store_branch.City
                </td>
                <td>
                    @Html.ActionLink("Удалить", "Delete", "StoreBranches", new { id = store_branch.Id }, new { })
                    @Html.ActionLink("Изменить", "Edit", "StoreBranches", new { id = store_branch.Id }, new { })
                </td>
            </tr>
        }
    </tbody>
</table>