web-app-asp-net-mvc-code-first/Models/Entities/City.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace web_app_asp_net_mvc_code_first.Models.Entities
{
    public class City
    {
        /// <summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Название города
        /// </summary>    
        [Required]
        [Display(Name = "Название", Order = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Список филиалов
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<StoreBranch> StoreBranches { get; set; }
    }
}

web-app-asp-net-mvc-code-first/Controllers/CitiesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using web_app_asp_net_mvc_code_first.Models.Entities;
using web_app_asp_net_mvc_code_first.Models;

namespace web_app_asp_net_mvc_code_first.Controllers
{
    public class CitiesController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new StoreContext();
            var cities = db.Cities.ToList();

            return View(cities);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var city = new City();
            return View(city);
        }

        [HttpPost]
        public ActionResult Create(City model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new StoreContext();

            db.Cities.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Cities/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new StoreContext();
            var city = db.Cities.FirstOrDefault(x => x.Id == id);
            if (city == null)
                return RedirectPermanent("/Cities/Index");

            db.Cities.Remove(city);
            db.SaveChanges();

            return RedirectPermanent("/Cities/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new StoreContext();
            var city = db.Cities.FirstOrDefault(x => x.Id == id);
            if (city == null)
                return RedirectPermanent("/Cities/Index");

            return View(city);
        }

        [HttpPost]
        public ActionResult Edit(City model)
        {
            var db = new StoreContext();
            var city = db.Cities.FirstOrDefault(x => x.Id == model.Id);
            if (city == null)
                ModelState.AddModelError("Id", "Город не найден");

            if (!ModelState.IsValid)
                return View(model);

            MappingCity(model, city);

            db.Entry(city).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Cities/Index");
        }

        private void MappingCity(City sourse, City destination)
        {
            destination.Name = sourse.Name;
        }
    }
}

web-app-asp-net-mvc-code-first/Views/Cities/Create.cshtml
@using web_app_asp_net_mvc_code_first.Models.Entities
@model City

<h3>Жанр</h3>

@using (Html.BeginForm("Create", "Cities", FormMethod.Post))
{
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" />
    @Html.ActionLink("Отменить", "Index", "Cities")
}

web-app-asp-net-mvc-code-first/Views/Cities/Edit.cshtml
@using web_app_asp_net_mvc_code_first.Models.Entities
@model City

<h3>Город</h3>

@using (Html.BeginForm("Edit", "Cities", FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" />
    @Html.ActionLink("Отменить", "Index", "Cities")
}

web-app-asp-net-mvc-code-first/Views/Cities/Index.cshtml
@using web_app_asp_net_mvc_code_first.Models.Entities
@model List<City>

<h3>Города</h3>

@Html.ActionLink("Добавить запись", "Create", "Cities")

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                Название
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var city in Model)
        {
            <tr>
                <td>
                    @city.Name
                </td>
                <td>
                    @Html.ActionLink("Удалить", "Delete", "Cities", new { id = city.Id }, new { })
                    @Html.ActionLink("Изменить", "Edit", "Cities", new { id = city.Id }, new { })
                </td>
            </tr>
        }
    </tbody>
</table>